_one ={"url": "https://i.instagram.com/api/v1/accounts/read_msisdn_header/",
       'status': 'ok',
       "headers": {'Content-Type': 'application/json; charset=utf-8',
                   'Vary': 'Accept-Language, Cookie',
                   'Content-Language': 'en',
                   'Date': 'Mon, 01 Mar 2021 14:20:06 GMT',
                   'Strict-Transport-Security': 'max-age=31536000',
                   'Cache-Control': 'private, no-cache, no-store, must-revalidate',
                   'Pragma': 'no-cache', 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
                   'X-Frame-Options': 'SAMEORIGIN',
                   'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"', 'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}',
                   'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=',
                   'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
                   'X-Content-Type-Options': 'nosniff',
                   'X-XSS-Protection': '0', 'x-aed': '38',
                   'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
                   'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:06 GMT; Max-Age=31449600; Path=/; Secure, mid=YDz4FgABAAEsAhc17P2Dk5L_33O4; Domain=.instagram.com; expires=Wed, 01-Mar-2023 14:20:06 GMT; Max-Age=63072000; Path=/; Secure',
                   'X-FB-TRIP-ID': '1679558926', 'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600', 'Connection': 'keep-alive', 'Content-Length': '15'}
}

_two = {"url": "https://i.instagram.com/api/v1/accounts/msisdn_header_bootstrap/",
        'status': 'ok',
        "headers": {'Content-Type': 'application/json; charset=utf-8',
                    'Vary': 'Accept-Language, Cookie',
                    'Content-Language': 'en',
                    'Date': 'Mon, 01 Mar 2021 14:20:06 GMT',
                    'Strict-Transport-Security': 'max-age=31536000',
                    'Cache-Control': 'private, no-cache, no-store, must-revalidate',
                    'Pragma': 'no-cache', 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
                    'X-Frame-Options': 'SAMEORIGIN',
                    'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests",
                    'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"',
                    'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}',
                    'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=',
                    'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
                    'X-Content-Type-Options': 'nosniff',
                    'X-XSS-Protection': '0',
                    'x-aed': '38',
                    'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
                    'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:06 GMT; Max-Age=31449600; Path=/; Secure',
                    'X-FB-TRIP-ID': '1679558926',
                    'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600',
                    'Connection': 'keep-alive', 'Content-Length': '15'}
        }
_three = {
             "url": "https://i.instagram.com/api/v1/zr/token/result/",
             "data":{'token':
                          {'carrier_name': '',
                           'carrier_id': 0,
                           'ttl': 72000,
                           'features': [],
                           'request_time': 1614608406,
                           'token_hash': '',
                           'rewrite_rules': [],
                           'enabled_wallet_defs_keys': [],
                           'deadline': '',
                           'zero_cms_fetch_interval_seconds': 86400,
                           'carrier_signal_config': []},
                     'status': 'ok'},
             "headers": {
                 'Content-Type': 'application/json; charset=utf-8', 'Vary': 'Accept-Language, Cookie, Accept-Encoding',
                 'Content-Language': 'en', 'Date': 'Mon, 01 Mar 2021 14:20:06 GMT',
                 'Content-Encoding': 'gzip',
                 'Strict-Transport-Security': 'max-age=31536000',
                 'Cache-Control': 'private, no-cache, no-store, must-revalidate',
                 'Pragma': 'no-cache',
                 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
                 'X-Frame-Options': 'SAMEORIGIN',
                 'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"', 'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}', 'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=', 'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
                 'X-Content-Type-Options': 'nosniff',
                 'X-XSS-Protection': '0',
                 'x-aed': '38',
                 'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
                 'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:06 GMT; Max-Age=31449600; Path=/; Secure',
                 'X-FB-TRIP-ID': '1679558926',
                 'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600',
                 'Connection': 'keep-alive',
                 'Content-Length': '193'}
}

_four = {
    "url": "https://i.instagram.com/api/v1/accounts/contact_point_prefill/",
    'status': 'ok',
    "headers": {
        'Content-Type': 'application/json; charset=utf-8',
        'Vary': 'Accept-Language, Cookie',
        'Content-Language': 'en', 'Date': 'Mon, 01 Mar 2021 14:20:07 GMT',
        'Strict-Transport-Security': 'max-age=31536000',
        'Cache-Control': 'private, no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
        'X-Frame-Options': 'SAMEORIGIN',
        'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"', 'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}', 'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=', 'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'x-aed': '38', 'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim', 'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:07 GMT; Max-Age=31449600; Path=/; Secure', 'X-FB-TRIP-ID': '1679558926', 'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600',
        'Connection': 'keep-alive',
        'Content-Length': '15'}
    }

_five = {
    "url": "https://i.instagram.com/api/v1/launcher/sync/",
            "data": {
                'configs':
                    {'ig_fbns_blocked':
                         {'params':
                              {'is_enabled':
                                   {'value': False},
                               'config_url': {'value': 'mqtt-gw.pushnotifs.com'}}
                          }, 'ig_android_felix_release_players':
                        {'params':
                             {'is_enabled': {'value': False}}
                         },
                     'ig_user_mismatch_soft_error':
                         {'params': {'crash_enabled': {'value': False}}
                          },
                     'ig_android_carrier_signals_killswitch':
                         {'params':
                              {'is_enabled': {'value': True}}
                          },
                     'ig_android_killswitch_perm_direct_ssim':
                         {'params': {'is_enabled': {'value': True}}
                          },
                     'fizz_ig_android': {
                         'params': {'is_enabled': {'value': True}}
                     },
                     'ig_mi_block_expired_events': {
                         'params': {'should_block': {'value': True}}}
                     }, 'status': 'ok'},
    "headers": {
        'Content-Type': 'application/json; charset=utf-8',
        'ig-set-password-encryption-key-id': '87',
        'ig-set-password-encryption-pub-key': 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4QTNCMnlhZ2s0Z0JXZGtVRk1PRgpCQVp0YTYwZ1dmREtoRjdXWThsREQvcFJtYm9paTFiTTlOK2l3anBVT1l6d3VPOWZ4eDdpZUdzQmVSYmxMQWFlCnhMU2lVekxnTnk1ZWpsYUJrZW44cjYweVVISXpUSXppL2J0cVFCZzlmci9LNnQ5RDFvc3Z1NkRrRmw0OTBtSWQKVHQ2dThkbjAyRzRocXVEa1dXa2sxazRHd0VQMVFOSG5XRVBJVWhuV0RzdGYzNVlkUUdXNFJFTEtOOWIvY0VtYQpTWVZ3eC8yZ1dodmVubEtRaVBKMUhmSDd3ZzdxYVNLdEdaaVRPeXJNMkJ0dDVzdU9lOCtIYmpJTURrdE10bkV0CjZBL0psTWtPbXhpSDEwV0RrbDVYUXRHL3JiVmRCZTR1VjNuR2hJL0kxWXBxV2FhdDZ1NmYrRUcyaUxlV053N0kKMHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==',
        'Vary': 'Accept-Language, Cookie, Accept-Encoding',
        'Content-Language': 'en',
        'Date': 'Mon, 01 Mar 2021 14:20:07 GMT',
        'Content-Encoding': 'gzip',
        'Strict-Transport-Security': 'max-age=31536000',
        'Cache-Control': 'private, no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
        'X-Frame-Options': 'SAMEORIGIN',
        'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests",
        'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"',
        'report-to': '{"group": "coep", "max_age": 86400, '
                     '"endpoints": '
                     '[{"url": "/security/coep_report/"}]},'
                     '{"group": "coop", "max_age": 86400, '
                     '"endpoints": '
                     '[{"url": "/security/coop_report/"}]}',
        'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=',
        'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
        'X-Content-Type-Options': 'nosniff',
        'X-XSS-Protection': '0',
        'x-aed': '38',
        'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
        'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:07 GMT; Max-Age=31449600; Path=/; Secure',
        'X-FB-TRIP-ID': '1679558926',
        'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600', 'Connection': 'keep-alive', 'Content-Length': '239'
    }
}
_six = {"url":"https://i.instagram.com/api/v1/qe/sync/",
        "data": {
            'experiments':
                [{'name': 'ig_android_direct_add_direct_to_android_native_photo_share_sheet',
                  'group': 'test',
                  'additional_params': [],
                  'params':
                      [{'name': 'is_enabled', 'value': 'true'}]
                  },
                 {'name': 'ig_android_login_identifier_fuzzy_match',
                  'group': 'edit2',
                  'additional_params': [],
                  'params': [{'name': 'enabled', 'value': 'true'},
                             {'name': 'cost', 'value': '2'}]},
                 {'name': 'ig_android_mas_remove_close_friends_entrypoint',
                  'group': 'test',
                  'additional_params': [],
                  'params':
                      [{'name': 'is_remove_entrypoint_enabled', 'value': 'true'}]
                  },
                 {'name': 'ig_android_direct_send_like_from_notification',
                  'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'is_send_inline_like_enabled', 'value': 'true'}]
                  },
                 {'name': 'ig_activation_global_discretionary_sms_holdout',
                  'group': 'control',
                  'additional_params': [],
                  'params': [{'name': 'hsite_can_stop_lookups', 'value': 'false'},
                             {'name': 'hsite_prefill_holdout_group', 'value': 'control'}]
                  },
                 {'name': 'ig_android_video_ffmpegutil_pts_fix',
                  'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'retry_count', 'value': '5'}]
                  },
                 {'name': 'ig_android_multi_tap_login_new',
                  'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'show_logged_out_only', 'value': 'true'},
                             {'name': 'enabled', 'value': 'true'}]},
                 {'name': 'ig_android_mas_notification_badging_universe', 'group': 'launch', 'additional_params': [],
                  'params': [{'name': 'show_feed_badge', 'value': 'false'},
                             {'name': 'show_badge', 'value': 'true'},
                             {'name': 'in_experiment', 'value': 'true'}]},
                 {'name': 'ig_android_sim_info_upload', 'group': 'test', 'additional_params': [],
                  'params': [{'name': 'enable_upload', 'value': 'true'}]},
                 {'name': 'ig_android_targeted_one_tap_upsell_universe', 'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'show_upsell', 'value': 'true'},
                             {'name': 'dialog', 'value': '0'}]},
                 {'name': 'ig_android_gmail_oauth_in_reg', 'group': 'rollout_1201',
                  'additional_params': [],
                  'params': [{'name': 'try_background_confirm', 'value': 'true'}]},
                 {'name': 'ig_android_family_apps_user_values_provider_universe', 'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'should_provide_user_values', 'value': 'true'}]},
                 {'name': 'ig_android_passwordless_account_password_creation_universe',
                  'group': 'test_one_tap_check_box_hidden',
                  'additional_params': [],
                  'params': [{'name': 'show_save_password_checkbox', 'value': 'true'},
                             {'name': 'upsell_for_mac_flow', 'value': 'false'}]},
                 {'name': 'ig_android_ask_for_permissions_on_reg', 'group': 'test_phone_only',
                  'additional_params': [],
                  'params': [{'name': 'email', 'value': 'false'},
                             {'name': 'phone', 'value': 'true'}]},
                 {'name': 'ig_android_security_intent_switchoff', 'group': 'allusers',
                  'additional_params': [],
                  'params': [{'name': 'switch_offs', 'value': ''}]},
                 {'name': 'ig_android_modularized_dynamic_nux_universe', 'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'enabled', 'value': 'true'}]},
                 {'name': 'ig_android_fb_account_linking_sampling_freq_universe', 'group': 'control',
                  'additional_params': [],
                  'params': [{'name': 'freq', 'value': '100'}]},
                 {'name': 'ig_android_fix_sms_read_lollipop', 'group': 'test',
                  'additional_params': [],
                  'params': [{'name': 'enabled', 'value': 'true'}]}],
            'status': 'ok'},
        "headers": {
            'Content-Type': 'application/json; charset=utf-8',
            'ig-set-password-encryption-key-id': '87',
            'ig-set-password-encryption-pub-key': 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4QTNCMnlhZ2s0Z0JXZGtVRk1PRgpCQVp0YTYwZ1dmREtoRjdXWThsREQvcFJtYm9paTFiTTlOK2l3anBVT1l6d3VPOWZ4eDdpZUdzQmVSYmxMQWFlCnhMU2lVekxnTnk1ZWpsYUJrZW44cjYweVVISXpUSXppL2J0cVFCZzlmci9LNnQ5RDFvc3Z1NkRrRmw0OTBtSWQKVHQ2dThkbjAyRzRocXVEa1dXa2sxazRHd0VQMVFOSG5XRVBJVWhuV0RzdGYzNVlkUUdXNFJFTEtOOWIvY0VtYQpTWVZ3eC8yZ1dodmVubEtRaVBKMUhmSDd3ZzdxYVNLdEdaaVRPeXJNMkJ0dDVzdU9lOCtIYmpJTURrdE10bkV0CjZBL0psTWtPbXhpSDEwV0RrbDVYUXRHL3JiVmRCZTR1VjNuR2hJL0kxWXBxV2FhdDZ1NmYrRUcyaUxlV053N0kKMHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==',
            'Vary': 'Accept-Language, Cookie, Accept-Encoding',
            'Content-Language': 'en',
            'Date': 'Mon, 01 Mar 2021 14:20:07 GMT',
            'Content-Encoding': 'gzip',
            'Strict-Transport-Security': 'max-age=31536000',
            'Cache-Control': 'private, no-cache, no-store, must-revalidate',
            'Pragma': 'no-cache',
            'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
            'X-Frame-Options': 'SAMEORIGIN',
            'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"', 'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}',
            'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=',
            'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
            'X-Content-Type-Options': 'nosniff',
            'X-XSS-Protection': '0',
            'x-aed': '38',
            'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
            'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:07 GMT; Max-Age=31449600; Path=/; Secure',
            'X-FB-TRIP-ID': '1679558926',
            'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600',
            'Connection': 'keep-alive', 'Content-Length': '744'
        }
        },

_seven = {"url": "https://i.instagram.com/api/v1/attribution/log_attribution/",
          'status': 'ok',
          "headers": {
              'Content-Type': 'application/json; charset=utf-8',
              'Vary': 'Accept-Language, Cookie',
              'Content-Language': 'en',
              'Date': 'Mon, 01 Mar 2021 14:20:07 GMT',
              'Strict-Transport-Security': 'max-age=31536000',
              'Cache-Control': 'private, no-cache, no-store, must-revalidate',
              'Pragma': 'no-cache',
              'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
              'X-Frame-Options': 'SAMEORIGIN',
              'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"', 'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}',
              'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=',
              'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
              'X-Content-Type-Options': 'nosniff',
              'X-XSS-Protection': '0',
              'x-aed': '38',
              'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
              'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:07 GMT; Max-Age=31449600; Path=/; Secure',
              'X-FB-TRIP-ID': '1679558926',
              'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600',
              'Connection': 'keep-alive',
              'Content-Length': '15'}
          }
_eight = {"url": "https://i.instagram.com/api/v1/accounts/get_prefill_candidates/",
          "data": {
              'prefills':
                  [{'usage': 'account_recovery_omnibox', 'candidates': []}],
              'status': 'ok'},
          "headers":
              {
                  'Content-Type': 'application/json; charset=utf-8',
                  'Vary': 'Accept-Language, Cookie',
                  'Content-Language': 'en',
                  'Date': 'Mon, 01 Mar 2021 14:20:07 GMT',
                  'Strict-Transport-Security': 'max-age=31536000',
                  'Cache-Control': 'private, no-cache, no-store, must-revalidate',
                  'Pragma': 'no-cache',
                  'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT',
                  'X-Frame-Options': 'SAMEORIGIN',
                  'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'cross-origin-embedder-policy-report-only': 'require-corp;report-to="coep"', 'report-to': '{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}',
                  'origin-trial': 'AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=',
                  'cross-origin-opener-policy': 'same-origin-allow-popups;report-to="coop"',
                  'X-Content-Type-Options': 'nosniff',
                  'X-XSS-Protection': '0',
                  'x-aed': '38',
                  'Access-Control-Expose-Headers': 'X-IG-Set-WWW-Claim',
                  'Set-Cookie': 'csrftoken=qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx; Domain=.instagram.com; expires=Mon, 28-Feb-2022 14:20:07 GMT; Max-Age=31449600; Path=/; Secure',
                  'X-FB-TRIP-ID': '1679558926',
                  'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600',
                  'Connection': 'keep-alive',
                  'Content-Length': '81'}}

#PWD_INSTAGRAM:4:1614608408:AQAAVwAAAAAAAAAAAAAAAAEAi4Sl4o7ZCX+GzRQDf5KINJtme/JwB6zBdA80dCuUjcoJPZK94ib5DSyyEcrXUsnlns8q8B7G/PsYS7Q+QG2KMpuGaS7PRq8zOfk6R01zc6BowTfKR2FYn/ZKT05/7vEi7yfFFZvaBQGwSX7sgw3qukYAjn0I0ABbsUHIZD13hNTwerCvQObjEVmtEkocOCrvBAmd5m4UDO8XntRQCs2BbXBVI6tBkGzHw8SbMYsNArnRtVzeTeFxF7hoLR2HZJ4ecCuduB22Vt42Naq7btGj4a1rU9BOIff22al7MAnnNi+qEKYBuA+2mt82EX1qSOxdDjqhZMsMCMR0irIySs1virCm8wnress2NszfHUYsAa/jxUY7Lt+veIKkkp23
request = {'account_data': {'password': 'ufeltfvec3500',
                  'username': 'rumych2013@gmail.com'},
 'adid': '',
 'advertising_id': '13b29d8c-b0c6-4ea0-a25e-0a2d3884d262',
 'authorization': '',
 'build_device': '23/6.0; 320dpi; 720x1208; HUAWEI/Huawei; ALE-L23; hwALE-H; '
                 'hi6210sft',
 'client_session_id': '45ba693a-e8da-45c9-8e95-777ffcf74183',
 'country_codes': '{"country_code": "1", "source": "default"}',
 'csrftoken': 'qzPpwb01Y0QNNmBdcWYn6Mj7zIUECHEx',
 'device_id': 'android-9adb218fe5fbdc21',
 'device_settings': {'android_release': '6.0.1',
                     'android_version': 23,
                     'app_version': '121.0.0.29.119',
                     'cpu': 'h1',
                     'device': 'RS988',
                     'dpi': '640dpi',
                     'manufacturer': 'LGE/lge',
                     'model': 'h1',
                     'resolution': '1440x2392',
                     'version_code': '185203708'},
 'ds_user_id': '',
 'enc_password': '#PWD_INSTAGRAM:4:1614608408:AQAAVwAAAAAAAAAAAAAAAAEAi4Sl4o7ZCX+GzRQDf5KINJtme/JwB6zBdA80dCuUjcoJPZK94ib5DSyyEcrXUsnlns8q8B7G/PsYS7Q+QG2KMpuGaS7PRq8zOfk6R01zc6BowTfKR2FYn/ZKT05/7vEi7yfFFZvaBQGwSX7sgw3qukYAjn0I0ABbsUHIZD13hNTwerCvQObjEVmtEkocOCrvBAmd5m4UDO8XntRQCs2BbXBVI6tBkGzHw8SbMYsNArnRtVzeTeFxF7hoLR2HZJ4ecCuduB22Vt42Naq7btGj4a1rU9BOIff22al7MAnnNi+qEKYBuA+2mt82EX1qSOxdDjqhZMsMCMR0irIySs1virCm8wnress2NszfHUYsAa/jxUY7Lt+veIKkkp23',
 'google_tokens': '[]',
 'igWWWClaim': '',
 'ig_did': '',
 'initialization_parameters': {},
 'jazoest': '22311',
 'login_attempt_count': 0,
 'mid': 'YDz4FgABAAEsAhc17P2Dk5L_33O4',
 'password': 'ufeltfvec3500',
 'passwordEncryptionKeyId': 87,
 'passwordEncryptionPubKey': 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4QTNCMnlhZ2s0Z0JXZGtVRk1PRgpCQVp0YTYwZ1dmREtoRjdXWThsREQvcFJtYm9paTFiTTlOK2l3anBVT1l6d3VPOWZ4eDdpZUdzQmVSYmxMQWFlCnhMU2lVekxnTnk1ZWpsYUJrZW44cjYweVVISXpUSXppL2J0cVFCZzlmci9LNnQ5RDFvc3Z1NkRrRmw0OTBtSWQKVHQ2dThkbjAyRzRocXVEa1dXa2sxazRHd0VQMVFOSG5XRVBJVWhuV0RzdGYzNVlkUUdXNFJFTEtOOWIvY0VtYQpTWVZ3eC8yZ1dodmVubEtRaVBKMUhmSDd3ZzdxYVNLdEdaaVRPeXJNMkJ0dDVzdU9lOCtIYmpJTURrdE10bkV0CjZBL0psTWtPbXhpSDEwV0RrbDVYUXRHL3JiVmRCZTR1VjNuR2hJL0kxWXBxV2FhdDZ1NmYrRUcyaUxlV053N0kKMHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==',
 'phone_id': '02db077a-5091-4a1c-9b72-cb5d207a5649',
 'username': 'rumych2013@gmail.com',
 'uuid': '17b77896-0912-401b-804b-de025ae89990'}

headers = {'Accept-Encoding': 'gzip',
 'Accept-Language': 'en_US',
 'Host': 'i.instagram.com',
 'User-Agent': 'Instagram 121.0.0.29.119 Android 24/7.0; 480dpi; 1080x1776; '
               'motorola; Moto G (5); cedric; qcom; en_US; 185203708 ',
 'X-Bloks-Is-Layout-RTL': 'false',
 'X-Bloks-Version-Id': '1b030ce63a06c25f3e4de6aaaf6802fe1e76401bc5ab6e5fb85ed6c2d333e0c7',
 'X-CM-Bandwidth-KBPS': '-1.000',
 'X-CM-Latency': '-1.000',
 'X-FB-HTTP-Engine': 'Liger',
 'X-IG-Android-ID': 'android-9adb218fe5fbdc21',
 'X-IG-App-ID': '567067343352427',
 'X-IG-App-Locale': 'en_US',
 'X-IG-Bandwidth-Speed-KBPS': '9086.797',
 'X-IG-Bandwidth-TotalBytes-B': '0',
 'X-IG-Bandwidth-TotalTime-MS': '0',
 'X-IG-Capabilities': '3brTvwM=',
 'X-IG-Connection-Speed': '2930-1kbps',
 'X-IG-Connection-Type': 'WIFI',
 'X-IG-Device-ID': '17b77896-0912-401b-804b-de025ae89990',
 'X-IG-Device-Locale': 'en_US',
 'X-IG-Mapped-Locale': 'en_US',
 'X-MID': 'YDz4FgABAAEsAhc17P2Dk5L_33O4',
 'X-Pigeon-Rawclienttime': '1614608406.282',
 'X-Pigeon-Session-Id': '3b14b0e8-16e2-43b6-93f0-963396d26c39'}